# Generated by Django 2.0.4 on 2018-06-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('num', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': '年报',
                'verbose_name_plural': '所有年报',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '所有用户',
            },
        ),
    ]
