# Generated by Django 2.0.4 on 2018-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('cid', models.AutoField(default='', primary_key=True, serialize=False)),
                ('cnum', models.CharField(max_length=10)),
                ('csname', models.CharField(max_length=10)),
                ('cfname', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '所有公司',
            },
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('rid', models.AutoField(default='', primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': '年报',
                'verbose_name_plural': '所有年报',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(default='', primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('creatdate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '所有用户',
            },
        ),
    ]
