# Generated by Django 2.0.4 on 2018-07-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180715_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rcp',
            field=models.ForeignKey(default=111111, on_delete=django.db.models.deletion.CASCADE, to='index.company'),
            preserve_default=False,
        ),
    ]
