# Generated by Django 2.0.4 on 2018-07-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_report_rcp'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('newdate', models.DateField(auto_now_add=True)),
                ('newtext', models.TextField()),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '所有动态',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='new',
            name='ncp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.company'),
        ),
    ]
