# Generated by Django 2.0.4 on 2018-07-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180715_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filename',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
