# Generated by Django 2.0.4 on 2018-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180730_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rdate',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rtitle',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rtype',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
